# Generated by Django 3.2.6 on 2021-08-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accent_collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_capital',
            field=models.BooleanField(default=None),
        ),
    ]
