---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sotaque-api-pvc
  name: sotaque-api-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
