name: Build and deploy back-end

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/backend.yaml"
      - "backend/**/*"
      - "kubernetes/**/*"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: us-central1-c

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configure Docker with gcloud
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Build Docker image
        run: |-
          cd ./backend/brazilian_regional_accent/
          docker build \
            --tag "gcr.io/$PROJECT_ID/sotaque-brasileiro-api:${{ github.sha }}" \
            .

      - name: Publish Docker image
        run: |-
          docker push "gcr.io/$PROJECT_ID/sotaque-brasileiro-api:${{ github.sha }}"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy
        run: |-
          ./kustomize edit set image gabrielmilan/GITHUB_REPO/api:GITHUB_SHA=gcr.io/$PROJECT_ID/sotaque-brasileiro-api:${{ github.sha }}
          ./kustomize build . | kubectl apply -n sotaque-brasileiro -f -
